### PR TITLE
Remove code dependent on tasks

### PR DESCRIPTION
**Pull request by delkopiso**
# What's up
The task feature isn't being used anymore, and hasn't been used for a while. This is now an irrelevant feature because each developer is working on a product team where their tasks are handled by iteration planning tools such as PivotalTracker, Trello, or Zenhub.

# What this does
- Removes the routes, models, specs and controllers for tasks, task_completions and comments
- Removes the task models

### CODE REVIEW

**Comment by delkopiso** [comment]
@abepetrillo review?

**Comment by abepetrillo** [comment]
Given this is open source, would we not want to keep the feature for other teams outside of alphasights?

**Comment by delkopiso** [comment]
Hmm, that's a good question. I think it's better to just have the singular focus of commits and pull requests.

**Comment by abepetrillo** [comment]
:+1:

**Pull request merged**
