### PR TITLE
Remove omniauth

### PR DESCRIPTION
**Pull request by matteodepalo**
# What's up
The current authentication scheme employs OAuth2 to authenticate against Github. The `omniauth` gem provides the bulk of this functionality. But https://developer.github.com/v3/oauth/ recommends a better web application authentication flow which wouldn't need to lean so heavily on `omniauth`.

# What this does
- Updates ruby to 2.2.0
- Removes `omniauth`, `omniauth-github` and `guard` gems
- Adds migration to create access_tokens table
- Updates routes, models and controllers to use the new token based authentication mechanism.

### CODE REVIEW

**Comment by delkopiso** [comment]
This PR is paired with https://github.com/alphasights/lion/pull/10

**Comment by delkopiso** [comment]
@willrax review?

**Comment by willrax** [comment]
LGTM :shipit: 

@delkopiso do you think its worth dropping the sql structure and going back to the schema (in another PR)?

**Comment by delkopiso** [comment]
@willrax Yeah I don't see why not.

**Comment by willrax** [comment]
:+1: I think you're good to ship anyway :dancers:

**Pull request merged**
